### ISSUE TITLE
keras version

### ISSUE THREAD

**Issue by wellescastro** [hfawaz/miccai18#3]
Hi! Great work.
Did you use keras 2.2.2 or keras 2.1.2? I couldn't find the version 2.12.2 so I suppose its something between the first two versions.

Thanks in advance,
Dayvid Castro.

**Comment by hfawaz** [comment]
Hello, 

Thank you for your interest! 

We used keras 2.1.2 yes, but any newer version should also work. 

Good luck !

**Comment by wellescastro** [comment]
Okay, thank you :)
